### ISSUE TITLE
Some problems on `/grdm/setTimeWindow`?

### ISSUE THREAD

**Issue by Lowerce** [jintonic/gears#10]
When I use `/grdm/setTimeWindow` for the simulation of decay chain, 
I found that only some time-window **beyond** one second can be splitted exactly. 
It seems the time-window **below** one second like nanosecond or microsecond can not be splitted precisely, 
because the outputs of these conditions are the same as one second condition, 
and there are more than one `dt` beyond the time-window in the same line(in the output file). 
If there is something wrong on my setting?   Hope for your answer!

Lowerce

**Comment by jintonic** [comment]
Could you please show me how you used `/grdm/setTimeWindow`? Did you use it like `/grdm/setTimeWindow 1 ns`?

**Comment by Lowerce** [comment]
I used it right.
I transplanted the important part of gears (to simulate the deposited energy of splitted decay chain in scintillation) to a basic example of Geant4.
I just made a test of **gears** on MacOS and Ubuntu, and I can not execute the code in your link exactly, after input of all commands, the window will shut down on both of systems.
I attached my code below (it's not complex because it's all based on B1 example and your gears code), if you want, you can build it and execute it, you only need to set the time window and beam on in the UI. 
All the problems came from my code, it works for the output of information, but the information may not totally right like what I said before.
Thanks a lot for your reply, hope for your further answer!
[NaI.zip](https://github.com/jintonic/gears/files/6369329/NaI.zip)

**Comment by jintonic** [comment]
How did you use GEARS on Mac and Ubuntu? Can you try the following in a terminal?
```
$ cd /path/to/gears/example/physics/decay
$ gears Pb201.mac
```
If the job quits with error message, please show me the message.

I can build and run your code. However, `/tracking/verbose 2` does not give me the standard information. I don't know how to interpret the output from your codes, which is simply a series of numbers.

**Comment by Lowerce** [comment]
Thanks a lot for your kindly help!

I tried your command and **gears** can work now. 
In order to test the problem I said before, I used `/grdm/setTimeWindow 1 ns` to ouput the root file and made a comparison of 1s and 1ns. I think it's totally the same in the output file.
(I use Th232 source to do the test for some decay process are below 1 second)
All the code I do the test and the output file are attached below.
[test.zip](https://github.com/jintonic/gears/files/6374830/test.zip)

I'm sorry for not describing my code detailed. After set the time window and beam on, a `NaI_Spec.csv` file will appear on the build folder. This file record almost the same information as the root file generated by **gears**. 

I do not know if I understand the output information right. But different time window setting causing the same output did confuse me. 

Thanks again for your patiently help, hope for your further explanation!

**Comment by jintonic** [comment]
Half life times for most of isotopes in the Th232 decay chain are longer than 1 second. For sure, 1 ns and 1 second time window will give you the same result. You may have some chance to see some differences in case of 216Po or 212Po, which have shorter than 1 second half lives. To see the difference clearly, you can compare the results with and without `/grdm/setTimeWindow 1 s`. The following is from GEARS:

### without 1 second time window

```
root [1] t->Scan("pdg:trk:pid:stp:dt/1e9:t/1e9","","colsize=10 precision=10")
*****************************************************************************************************
*    Row   * Instance *        pdg *        trk *        pid *        stp *     dt/1e9 *      t/1e9 *
*****************************************************************************************************
*        0 *        0 * 1000902320 *          1 *          0 *          0 *          0 *          0 *
*        0 *        1 * 1000902320 *          1 *          0 *          1 * 1.3902e+18 * 1.3902e+18 *
*        0 *        2 * 1000020040 *          3 *          1 *          0 *          0 * 1.3902e+18 *
*        0 *        3 * 1000020040 *          3 *          1 *          1 * 8.7711e-13 * 1.3902e+18 *
*        0 *        4 * 1000882280 *          2 *          1 *          0 *          0 * 1.3902e+18 *
*        0 *        5 * 1000882280 *          2 *          1 *          1 * 3.2388e-15 * 1.3902e+18 *
*        0 *        6 * 1000882280 *          2 *          1 *          2 * 78638424.4 * 1.3902e+18 *
```

### with 1 second time window

```
root [1] t->Scan("pdg:trk:pid:stp:dt/1e9:t/1e9","","colsize=10 precision=10")
*****************************************************************************************************
*    Row   * Instance *        pdg *        trk *        pid *        stp *     dt/1e9 *      t/1e9 *
*****************************************************************************************************
*        0 *        0 * 1000902320 *          1 *          0 *          0 *          0 *          0 *
*        0 *        1 * 1000902320 *          1 *          0 *          1 * 1.3902e+18 * 1.3902e+18 *
*        1 *        0 * 1000020040 *          3 *          1 *          0 *          0 * 1.3902e+18 *
*        1 *        1 * 1000020040 *          3 *          1 *          1 * 8.7711e-13 * 1.3902e+18 *
*        1 *        2 * 1000882280 *          2 *          1 *          0 *          0 * 1.3902e+18 *
*        1 *        3 * 1000882280 *          2 *          1 *          1 * 3.2388e-15 * 1.3902e+18 *
*        1 *        4 * 1000882280 *          2 *          1 *          2 * 78638424.4 * 1.3902e+18 *
```

You can see that without time window setup, Ac228 is in the some event as Th232 (row numbers are all 0). With time window, Ac228 is split to another event (row number is 1 instead of 0).

**Comment by Lowerce** [comment]
Yes, you are right. 
There is no difference for Th232 to set the time window to 1ns and 1s for no such time of decay in the decay chain between both of them.
I have tried Po212 for 1ps time window, and **gears** can split it correctly.
Thanks again for your patient explanation!

**Comment by Lowerce** [comment]
Dear jintonic,
I found that the example of decay chain splitting can not process more than one shooting particle(`/run/beamOn`) correctly.
The shooting particle beyond one will be divided into one row.
Besides, the problem I said before may not come from your setTimeWindow code, even if setting a very small time window, some decay process also can not be divided when simulating full chain(like **Po216->Pb212** in Th232 chain or **Po214->Pb210** in U238 chain) for I have used some other way to split these process according to time but failed. I think it should be the physics problem of *Geant4*.

**Comment by jintonic** [comment]
Hi, Lowerce, you can simulate two decay chains in two separate Geant4 simulation jobs and then combine their output in your analysis code. This way, you don't have to start with two primary particles. It might be possible to update GEARS code to deal with two primaries, but I'd prefer to keep things simple if there is other solution. As for the second problem, if you believe it is really a Geant4 problem, please report it in the Geant4 forum. I am just a normal Geant4 user.

**Comment by Lowerce** [comment]
Thanks for your answer! 
**GEARS** code is a good pathway to learn the usage of **Geant4**, it helped a lot in my practice of **Geant4**!
