### ISSUE TITLE
G4AnalysisManager.hh gives error for geant4.10.7

### ISSUE THREAD

**Issue by Pely** [jintonic/gears#12]
Hi, 
I'm using geant version 10.7.2 and I wasn't able to compile your application. I received the following error 
```
fatal error: 'G4AnalysisManager.hh' file not found
#include <G4AnalysisManager.hh>
```
I replaced the `#include <G4AnalysisManager.hh>` with the #include `<g4root.hh>` and it compiled. However, I haven't tried to use the whole program yet.
Let me know if you have a different solution to this issue. 
Thank you

**Comment by jintonic** [comment]
Please read the first paragraph of the README file. The latest GEARS only works with Geant4.11. If you need to use older versions of Geant4 for some reason, please use a branch called g4.10.
