### ISSUE TITLE
simple Bremsstrahlung setup

### ISSUE THREAD

**Issue by berceanu** [jintonic/gears#14]
Hi,

I was wondering if/how `gears` could be used to simulate the following scenario:

Electrons (read from an input file) passing through a thick rectangular plate of Pb, generating photons through Bremsstrahlung

The outputs I would be interested in are the spectral and angular distribution of the Bremsstrahlung photons.

**Comment by jintonic** [comment]
GPS is what you need to implement source distribution from a file. Please read instructions on page <https://github.com/jintonic/gears/tree/master/tutorials/sources>. You may also need to use LBE_LIV physics model to have Bremsstrahlung enabled: https://github.com/jintonic/gears/tree/master/tutorials/physics.

**Comment by berceanu** [comment]
Thank you for the quick reply. Looking at the sources page, I could not find an example of how to read electrons from an input .hdf5 file that contains their positions and momenta, for example.
