### ISSUE TITLE
Qt error when compiling gears example application: -fPIC vs -fPIE

### ISSUE THREAD

**Issue by purpleflame** [jintonic/gears#17]
I have been following along your [guide for installing Geant4 on my WSL version2 instance of Ubuntu 22.04](https://www.youtube.com/watch?v=zBRLls4eC34). I made my way through each step just fine all the way through clone the gears repo. However, I got an error from Qt when running `make` in the cloned directory as instructed. It seems to be related to using `-fPIC` vs `-fPIE` during building. Since I did not see any such option among those listed, I am not sure how to proceed. I installed all the prerequisite libraries as instructed in that video.

    ali@xps8920:~/downloads/gears$ make
    g++ -DG4VIS_USE_OPENGL -DG4UI_USE_TCSH -DG4UI_USE_QT -DG4VIS_USE_OPENGLQT -DG4VIS_USE_TOOLSSG_QT_GLES -I/usr/include/x86_64-linux-gnu/qt5/ -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5//mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -DG4UI_USE_QT3D -DG4VIS_USE_RAYTRACERX -DG4VIS_USE_OPENGLX -DG4VIS_USE_TOOLSSG_X11_GLES -W -Wall -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-variadic-macros -Wshadow -pipe -pthread -ftls-model=initial-exec -std=c++17 -I/usr/local/include/Geant4    gears.cc  -L/usr/local/lib -lG4OpenGL -lG4visQt3D -lG4Tree -lG4FR -lG4GMocren -lG4visHepRep -lG4RayTracer -lG4VRML -lG4ToolsSG -lG4vis_management -lG4modeling -lG4interfaces -lG4geomtext -lG4mctruth -lG4analysis -lG4error_propagation -lG4readout -lG4physicslists -lG4run -lG4event -lG4tracking -lG4parmodels -lG4processes -lG4digits_hits -lG4track -lG4particles -lG4geometry -lG4materials -lG4graphics_reps -lG4intercoms -lG4global -lG4clhep -lG4zlib -lG4ptl -L/usr/local/lib -o gears
    In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtGlobal:1,
                     from /usr/local/include/Geant4/G4VisExecutive.icc:142,
                     from /usr/local/include/Geant4/G4VisExecutive.hh:141,
                     from gears.cc:649:
    /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1281:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (and not with -fPIE)."
     1281 | #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
          |    ^~~~~
    make: *** [<builtin>: gears] Error 1
    ali@xps8920:~/downloads/gears$

To check my version of Qt, here is qmake's output.

    ali@xps8920:~/downloads/gears$ qmake --version
    QMake version 3.1
    Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu
    ali@xps8920:~/downloads/gears$

I did a quick search and found this [very similar issue](https://stackoverflow.com/questions/15978608/qt-compile-your-code-with-fpic-or-fpie). It seems to me that I have to add the line `set_target_properties(gears PROPERTIES POSITION_INDEPENDENT_CODE TRUE)` to the CMakeLists.txt file. Trying that had no effect.

I would rather use WSL. However, I tried the Windows way: using the Cmake gui then building in Visual Studio. I got the following error on the guild step. I appreciate any advise on how to proceed.

![error-building-gears-20231211](https://github.com/jintonic/gears/assets/4513699/631f6aeb-a290-42ab-b29e-75c897c387fd)

**Comment by jintonic** [comment]
Thanks for your careful debugging! It seems that you directly used the Makefile instead of the CMakeLists.txt file for compiling gears. I added "-fPIC" to the cxxflag in Makefile. Please download the newest gears and try again. As for the compilation error in windows, it is because I accedentally deleted gears.bat file. I added it back. It should work now. By the way, the message about "size_t" can be safely ignored.

**Comment by purpleflame** [comment]
Thanks for getting back to me so quickly! I have some mostly positive news though I still need some help.

I went ahead and started fresh with a new clone of your github repo and ran make again with different errors this time.

    ali@xps8920:~/downloads/gears$ make
    g++ -DG4VIS_USE_OPENGL -DG4UI_USE_TCSH -DG4UI_USE_QT -DG4VIS_USE_OPENGLQT -DG4VIS_USE_TOOLSSG_QT_GLES -I/usr/include/x86_64-linux-gnu/qt5/ -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5//mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -DG4UI_USE_QT3D -DG4VIS_USE_RAYTRACERX -DG4VIS_USE_OPENGLX -DG4VIS_USE_TOOLSSG_X11_GLES -W -Wall -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-variadic-macros -Wshadow -pipe -pthread -ftls-model=initial-exec -std=c++17 -I/usr/local/include/Geant4 -fPIC    gears.cc  -L/usr/local/lib -lG4OpenGL -lG4visQt3D -lG4Tree -lG4FR -lG4GMocren -lG4visHepRep -lG4RayTracer -lG4VRML -lG4ToolsSG -lG4vis_management -lG4modeling -lG4interfaces -lG4geomtext -lG4mctruth -lG4analysis -lG4error_propagation -lG4readout -lG4physicslists -lG4run -lG4event -lG4tracking -lG4parmodels -lG4processes -lG4digits_hits -lG4track -lG4particles -lG4geometry -lG4materials -lG4graphics_reps -lG4intercoms -lG4global -lG4clhep -lG4zlib -lG4ptl -L/usr/local/lib -o gears
    /usr/bin/ld: /tmp/ccISA0Xb.o: undefined reference to symbol 'qt_version_tag@@Qt_5.15'
    /usr/bin/ld: /lib/x86_64-linux-gnu/libQt5Core.so.5: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    make: *** [<builtin>: gears] Error 1

Seems like it cannot find Qt5, maybe? (even though it was installed as a prerequisite per the guide).

From your response, I guess I was supposed to use `ccmake /path/to/CMakeLists.txt` before using make. `ccmake` took a while to search and eventually ended up with the following.

![image](https://github.com/jintonic/gears/assets/4513699/56cbd145-0af5-445f-b4a7-53fc19259788)

It seems odd to me that it would find Geant4 and Qt in those locations. Never-the-less, since it found them, I went a head and generated and ran `make`. It compiled without issue. I was able to copy the gears program to the system location per the guide. I was even able to run it and see a gui. Initially, I was unsure how to use it. Looks like the gui is there to help run "macro" commands interactively or a kind of batch/script mode via a `.mac` file.

![image](https://github.com/jintonic/gears/assets/4513699/5ea38a3b-2e8b-4b99-ba5b-43f049365f80)

The ASCIITree example worked great once I ran it from its directory. However, the RayTracer example gave an error when I ran it. Perhaps the Geant4 API changed since then?

    ali@xps8920:~/downloads/gears/tutorials/detector/visualization$ gears RayTracer.mac
    /vis/drawVolume
    /vis/scene/create
    /vis/scene/add/volume world -1 -1 none m 0 0 0 0 0 0
    /vis/sceneHandler/attach
    /vis/viewer/refresh
    WARNING: G4RayTracerViewer::DrawView: true orthogonal projection
      not yet implemented.  Doing a "long shot", i.e., a perspective
      projection with a half field angle of 1e-06 radians.
    /tracking/storeTrajectory 1
    Segmentation fault

P.S.  It looks like my `$PATH` variable is full of paths such as `/mnt/c/...`. Perhaps the WSL is stuck on the Windows locations and I might need to manually add in the Ubuntu paths. From the find command and the installation guide, it looks like the locations should be as follows, perhaps?

    /usr/include/x86_64-linux-gnu/qt5/QtCore/Qt
    geant4 data files: /usr/local/share/Geant4/data
    geant4 examples: /usr/local/share/Geant4/examples
    geant4 config: /usr/local/bin/geant4-config
    geant4 installed? /usr/local/sbin
    geant4 installed? /usr/local/bin
    geant4 installed? /usr/local
    geant4 header files /usr/local/include/Geant4
    geant4 libraries /usr/local/lib

**Comment by jintonic** [comment]
I am glad that `ccmake` worked for you. Please just forget about the direct `make` in that case.

Your Geant4 was installed to `/usr/local/`. CMake found the right location.

Yes, the Qt GUI is used to run macro files. To learn more about Geant4 UI, please read <https://github.com/jintonic/gears/tree/master/tutorials/UI>.

You may have not compiled Geant4 with RayTracerX11 support. Run `geant4-config --help` to check that.

WSL inherits PATH setting on the host Windows. If you don't like that, you can disable this behavior by editing `/ect/wsl.conf`:

```sh
# Set whether WSL supports interop processes like launching Windows apps and adding path variables. Setting these to false will block the launch of Windows processes and block adding $PATH environment variables.
[interop]
enabled = false
appendWindowsPath = false
```

**Comment by purpleflame** [comment]
I must have missed the step in the video where ccmake happened. I will remember that compiling has the `ccmake` > `make` > `make install` workflow.

Yea, that location leaves me uneasy. I saw you have a video on putting geant4 in my home directory. Hopefully it will help me move it. If not then I might just re-install it after I confirm test programs are working.

Thanks for the tutorial. I will check it out.

Good thought. However the response from `geant4-config --help` includes the line: `raytracer-x11[yes]`.

The `/etc/wsl.config` file did not exist. I liked the idea so I went ahead and made the file.

I already sourced that file in my `~/.bashrc` so that would be how it found it.

Many thanks for all your help!

**Comment by jintonic** [comment]
GEARS provides two ways to compile on Linux and MacOS, one is to directly type `make`, the other one is to go through `ccmake`. I only demonstrated the first way in my WSL video.

`/usr/local` is a perfect location for installing Geant4. If you don't like it, you can always go back to your geant4 source/build directory and type `make uninstall` to remove everything.

Regarding `raytracer`, it might be just WSL related. It may just work in a real Linux box. But I am just guessing.

You can for sure create `/etc/wsl.config` file by yourself.
