### ISSUE TITLE
Getting error with gps while using gears in windows 10

### ISSUE THREAD

**Issue by HitMan01KW9** [jintonic/gears#18]
_Geant4 Version:_11.2.0
_Operating System:_Windows 10
Compiler/Version: Visual Studio 2022
CMake Version: 3.28.1

I’ve started doing some simulations on Geant4 (the basic stuff) and tried to add a General Particle Source (GPS) to my simulation and Gears doesn’t seem to accept this macro. There’s another macro called gun that has essentially the same functionalities but not all. For example, I wanted my source to be isotropic and for that, the corresponding line of code is /gps/direction iso but when I tried doing that with gun it didn’t recognize the iso part.

Thanks in advance for any clarification about this issue.

As I understand, the gps macro should be defined within gears and I saw the guy doing the tutorial using the gps macro without any issues. I’m a bit lost in figuring out a way to tell gears to consider the .hh file for the gps rather than the one considered for gun.

**Comment by jintonic** [comment]
GEARS just use GPS provided by Geant4. By default, the emission is already isotropic. You don't have to do anything special. If you really want to do it explicitly, please read the text around <https://github.com/jintonic/gears/blob/master/tutorials/sources/gps.txt#L587>
