### ISSUE TITLE
Unable to produce ROOT file with GDML geometry

### ISSUE THREAD

**Issue by TWPHyatt** [jintonic/gears#19]
Hi,

I am trying to produce a ROOT output file from gears using the command in my macro file:
`/analysis/setFileName gears.root`

I have the problem that I cannot produce a ROOT output file using a GDML geometry source:
`/geometry/source` ... `/simple_box.gdml`

If I change the geometry definition to the one used in radiate.mac, I am able to produce a ROOT output file:
`/geometry/source` ... `/detector.tg`

Are there extra steps or commands to do this with a GDML geometry?

Thank you.

**Comment by jintonic** [comment]
Data output and geometry source are not connected in any way. Is your Geant4 compiled with GDML support? You can check that using `geant4-config --help`. If yes, did you shoot some particles to your geometry? If yes, did them leave some steps in volumes that have copy number>0? You can check that using `/tracking/verbose 2`
