### ISSUE TITLE
 G4PhysListFactory WARNING

### ISSUE THREAD

**Issue by mahmoodeid** [jintonic/gears#20]
Hi,

I have an issue with environment variable PHYSLIST. I built GEARS and Geant4-11.2.0 on Windows 11 using Cmake 3.22 and VS 2019. I have also defined the environment variables of the Geant4 bin and data using the batch file set.bat. The following error encountered:

```
### G4PhysListFactory WARNING:  environment variable PHYSLIST is not defined
    Default Physics Lists FTFP_BERT is instantiated
G4PhysListFactory::GetReferencePhysList <FTFP_BERT>  EMoption= 0
<<< Geant4 Physics List simulation engine: FTFP_BERT


/geometry/source geometry.tg
/physics_lists/select QGSP_BERT
G4PhysListFactory::GetReferencePhysList <QGSP_BERT>  EMoption= 0
<<< Geant4 Physics List simulation engine: QGSP_BERT


/physics_lists/factory/addRadioactiveDecay
***** COMMAND NOT FOUND </physics_lists/factory/addRadioactiveDecay> *****

***** Batch is interrupted!! *****

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : UIMAN0123
      issued by : G4UImanager::ApplyCommand
Command aborted (100)
Error code : 100
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

Do you think it is a problem of Geant-4 building? I have not observed any errors during the building of both Geant4 and GEARS.

**Comment by jintonic** [comment]
Geant4.11.2 removed the macro command `/physics_lists/factory/addRadioactiveDecay`. Everything is working as expected. Please read their release note for details, or ask them in Geant4 forum regarding this change.

**Comment by mahmoodeid** [comment]
Got it. May be should be noted in the decay examples. Thanks, a lot.
