### ISSUE TITLE
gears.exe User Interface too small

### ISSUE THREAD

**Issue by shivompa** [jintonic/gears#21]
On some lines of the User Interface, the first letter of the text will be cropped out by the lefthand border.
For example:
"ou have successfully registered..." 
"ype of de-excitation..."
"eometry factor for msc..."
How can I fix this?

![image](https://github.com/jintonic/gears/assets/77848523/043c6328-6650-425c-844f-ed2698686e02)

**Comment by jintonic** [comment]
Make the whole window larger, drag the split bar between the left and right panels, place your cursor in the right panel with a single left mouse button click and then use the right arrow key in your keyboard to move your cursor to the far right side, search for a horizontal scroll bar. This interface is provided by Geant4. GEARS is just using it. It is not a bug of GEARS.
