### ISSUE TITLE
failed compilation

### ISSUE THREAD

**Issue by gakabani** [jintonic/gears#22]
I need essential advice. Do I need to run CMAKE before make? 
I tried "make" as indicated but got many errors during compilation.

In file included from gears.cc:631:
In file included from /Users/gamalakabani/Codes/GEANT4/geant4-v11.2.1-install/include/Geant4/G4VisExecutive.hh:141:
In file included from /Users/gamalakabani/Codes/GEANT4/geant4-v11.2.1-install/include/Geant4/G4VisExecutive.icc:142:
In file included from /Users/gamalakabani/miniconda3/include/qt/QtCore/QtGlobal:1:
/Users/gamalakabani/miniconda3/include/qt/QtCore/qglobal.h:399:11: error: 'maybe_unused' attribute cannot be applied to types
constexpr Q_DECL_UNUSED Deprecated_t Deprecated = {};

**Comment by jintonic** [comment]
GEARS is shipped with both Makefile and CMakeLists.txt. They are independent from each other. If Makefile fails, you can try the CMake system. To do that, you need to run
```sh
cd /path/to/gears
cmake -B build
make -C build
```
or
```sh
cd /path/to/gears
mkdir build
cd build
cmake ..
make
```
The executable `gears` will be in the `build` folder.

**Comment by gakabani** [comment]
Dear Liu,

Thank you for your prompt help. It is very much appreciated.
Unfortunately, I got errors after testing the gears with the GDML file in
the "gears/tutorials/detector/GDML"
I may have some GEANT4 installation problems.

I am giving the output of gears below. I would appreciate any help you can
give me.

Thank you!!

%%gears export.mac

**************************************************************

 Geant4 version Name: geant4-11-02-patch-01 [MT]   (16-February-2024)

                       Copyright : Geant4 Collaboration

                      References : NIM A 506 (2003), 250-303

                                 : IEEE-TNS 53 (2006), 270-278

                                 : NIM A 835 (2016), 186-225

                             WWW : http://geant4.org/

**************************************************************


### G4PhysListFactory WARNING:  environment variable PHYSLIST is not defined

    Default Physics Lists FTFP_BERT is instantiated

G4PhysListFactory::GetReferencePhysList <FTFP_BERT>  EMoption= 0

<<< Geant4 Physics List simulation engine: FTFP_BERT



Visualization Manager instantiating with verbosity "warnings (3)"...

Visualization Manager initialising...

Registering graphics systems...


You have successfully registered the following graphics systems.

Registered graphics systems are:

  ASCIITree (ATree)

  DAWNFILE (DAWNFILE)

  G4HepRepFile (HepRepFile)

  RayTracer (RayTracer)

  VRML2FILE (VRML2FILE)

  gMocrenFile (gMocrenFile)

  TOOLSSG_OFFSCREEN (TSG_OFFSCREEN)

  TOOLSSG_OFFSCREEN (TSG_OFFSCREEN, TSG_FILE)

  OpenGLImmediateQt (OGLIQt, OGLI)

  OpenGLStoredQt (OGLSQt, OGL, OGLS)

  OpenGLImmediateX (OGLIX, OGLIQt_FALLBACK)

  OpenGLStoredX (OGLSX, OGLSQt_FALLBACK)

  RayTracerX (RayTracerX)

  Qt3D (Qt3D)

  TOOLSSG_X11_GLES (TSG_X11_GLES, TSGX11, TSG_QT_GLES_FALLBACK)

  TOOLSSG_QT_GLES (TSG_QT_GLES, TSGQt, TSG)

  TOOLSSG_QT_ZB (TSG_QT_ZB, TSGQtZB)

Default graphics system is: TSG_OFFSCREEN (based on batch session).

Default window size hint is: 600x600-0+0 (based on G4VisManager
initialisation).

Note: Parameters specified on the command line will override these defaults.

      Use "vis/open" without parameters to get these defaults.


Registering model factories...


You have successfully registered the following model factories.

Registered model factories:

  generic

  drawByAttribute

  drawByCharge

  drawByOriginVolume

  drawByParticleID

  drawByEncounteredVolume


Registered models:

  None


Registered filter factories:

  attributeFilter

  chargeFilter

  originVolumeFilter

  particleFilter

  encounteredVolumeFilter


Registered filters:

  None


You have successfully registered the following user vis actions.

Run Duration User Vis Actions: none

End of Event User Vis Actions: none

End of Run User Vis Actions: none


Some /vis commands (optionally) take a string to specify colour.

"/vis/list" to see available colours.

--- G4CoupledTransportation is used


 hInelastic FTFP_BERT : threshold between BERT and FTFP is over the interval


 for pions :   3 to 6 GeV

 for kaons :   3 to 6 GeV

 for proton :  3 to 6 GeV

 for neutron : 3 to 6 GeV


### Adding tracking cuts for neutron  TimeCut(ns)= 10000  KinEnergyCut(MeV)=
0

***** COMMAND NOT FOUND </geometry/export gears.gdml> *****


***** Batch is interrupted!! *****


-------- WWWW ------- G4Exception-START -------- WWWW -------

*** G4Exception : UIMAN0123

      issued by : G4UImanager::ApplyCommand

Command aborted (100)

Error code : 100

*** This is just a warning message. ***

-------- WWWW -------- G4Exception-END --------- WWWW -------


Graphics systems deleted.

Visualization Manager deleting...

(base) ***@***.*** GDML % ls -l

total 24

-rw-r--r--@ 1 gamalakabani  staff  373 Jul 23 20:19 README.md

-rw-r--r--  1 gamalakabani  staff   73 Jul 23 20:19 export.mac

-rw-r--r--  1 gamalakabani  staff  154 Jul 23 20:19 visualize.old.C

(


Gamal Akabani

**Comment by jintonic** [comment]
run `geant4-config --help` to see if GDML is enabled or not for your Geant4 installation. If it is not enabled, gears cannot do anything about it. gears just uses whatever function that is available in your Geant4 installation. I have a few YouTube tutorials about enabling GDML in Geant4 compilation process. Please follow them. I am closing this issue. It is not a GEARS issue.

**Comment by gakabani** [comment]
Dear Kiu,

Indeed, thank you for your help. I will look into it.

Gamal Akabani
